// Generated by Xata Codegen 0.23.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "books",
    columns: [
      {
        name: "name",
        type: "string",
        notNull: true,
        defaultValue: "Not Defined",
      },
      { name: "description", type: "text" },
      { name: "publishedAt", type: "datetime" },
      { name: "author", type: "link", link: { table: "authors" } },
      { name: "category", type: "link", link: { table: "categories" } },
    ],
  },
  {
    name: "authors",
    columns: [
      { name: "firstname", type: "string" },
      { name: "lastname", type: "string" },
      { name: "country", type: "string" },
      { name: "books", type: "link", link: { table: "books" } },
    ],
  },
  {
    name: "categories",
    columns: [
      { name: "name", type: "string" },
      { name: "description", type: "text" },
    ],
  },
  {
    name: "reviews",
    columns: [
      { name: "bookId", type: "link", link: { table: "books" } },
      { name: "comment", type: "text" },
      { name: "visible", type: "bool", notNull: true, defaultValue: "false" },
      { name: "publishedAt", type: "datetime" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Books = InferredTypes["books"];
export type BooksRecord = Books & XataRecord;

export type Authors = InferredTypes["authors"];
export type AuthorsRecord = Authors & XataRecord;

export type Categories = InferredTypes["categories"];
export type CategoriesRecord = Categories & XataRecord;

export type Reviews = InferredTypes["reviews"];
export type ReviewsRecord = Reviews & XataRecord;

export type DatabaseSchema = {
  books: BooksRecord;
  authors: AuthorsRecord;
  categories: CategoriesRecord;
  reviews: ReviewsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://jcdonis-s-workspace-2qn51r.us-east-1.xata.sh/db/the-geeks-corner",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
